#1. 연속형 vs 연속형 일떄는 피어슨 상관계수를 쓴다. 
# label이 명목형일때는 연관성을 어떻게 측정하는지 고찰 -> 스피어만 상관계수, 피어슨 상관계수가 뭔지 알아보자
#2. k-means를 통한 클러스터 파생변수 추가
#3. 파이캐럿 AutoML을 돌려서 상위 3개 모델을 선정
#4. catBoost를 블렌더 모델로 선정하여 전방 모델은 2번 상위모델 3개로 배치 = 스택킹
#5. 학습하여 test.csv를 찍어서 submission.csv를 제출
#6. 챗지피티 사용 가능하나, 랜덤뽑기로 설명하는 사람 선정

In [1]:
# pycaret 설치 확인 
from pycaret.classification import setup, compare_models
from sklearn.datasets import load_iris
import pandas as pd

data = load_iris(as_frame=True).frame
clf = setup(data=data, target='target', session_id=123)
best_model = compare_models()
print(best_model)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [2]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import RobustScaler, LabelEncoder
from sklearn.metrics import f1_score
import catboost as ctb
import lightgbm as lgb
import os
import datetime
import warnings
warnings.filterwarnings('ignore')

In [3]:
# 데이터 불러오기
train_df = pd.read_csv('train.csv')
test_df = pd.read_csv('test.csv')
# 상관 관계확인 ID & 나머지 columns / y = support_needs

In [4]:
train_df.head(5), test_df.head(5)

(            ID   age gender  tenure  frequent  payment_interval  \
 0  TRAIN_00000  54.0      F    47.0      22.0               8.0
 1  TRAIN_00001  30.0      M    16.0      15.0               5.0
 2  TRAIN_00002  29.0      M     8.0      30.0              21.0
 3  TRAIN_00003  38.0      F    38.0      23.0              10.0
 4  TRAIN_00004  25.0      F    52.0       3.0              17.0

   subscription_type  contract_length  after_interaction  support_needs
 0            member               90               25.0              0
 1               vip              360               23.0              0
 2              plus               30               21.0              0
 3               vip               90                6.0              0
 4            member               30                1.0              2  ,
            ID   age gender  tenure  frequent  payment_interval  \
 0  TEST_00000  18.0      M    40.0       6.0              15.0
 1  TEST_00001  40.0      M    41.0      23.0               0.0
 2  TEST_00002  59.0      F    30.0       1.0              21.0
 3  TEST_00003  38.0      M     2.0      10.0               0.0
 4  TEST_00004  30.0      M    28.0      21.0              20.0

   subscription_type  contract_length  after_interaction
 0            member               30               18.0
 1            member               90               16.0
 2            member              360               25.0
 3            member               30               18.0
 4            member              360               28.0  )

In [5]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30858 entries, 0 to 30857
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID                 30858 non-null  object
 1   age                30858 non-null  float64
 2   gender             30858 non-null  object
 3   tenure             30858 non-null  float64
 4   frequent           30858 non-null  float64
 5   payment_interval   30858 non-null  float64
 6   subscription_type  30858 non-null  object
 7   contract_length    30858 non-null  int64
 8   after_interaction  30858 non-null  float64
 9   support_needs      30858 non-null  int64
dtypes: float64(5), int64(2), object(3)
memory usage: 2.4+ MB

In [ ]:
train_df.columns
# ['ID', 'age', 'gender', 'tenure', 'frequent', 'payment_interval', 'subscription_type', 'contract_length', 'after_interaction']
# ['support_needs']

Index(['ID', 'age', 'gender', 'tenure', 'frequent', 'payment_interval',
       'subscription_type', 'contract_length', 'after_interaction',
       'support_needs'],
      dtype='object')

In [9]:
import scipy.stats as spearsonr

In [ ]:
X = train_df.drop(columns=['ID', 'support_needs'])
y = train_df['support_needs']

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [14]:
X_train.head()

,age,gender,tenure,frequent,payment_interval,subscription_type,contract_length,after_interaction
11378,19.0,M,27.0,29.0,2.0,plus,360,4.0
18706,19.0,F,57.0,18.0,18.0,member,90,17.0
23515,42.0,M,45.0,28.0,0.0,vip,90,24.0
11239,41.0,M,45.0,12.0,16.0,vip,360,5.0
15659,20.0,M,18.0,24.0,3.0,member,90,16.0

In [15]:
y_train.head()

11378    0
18706    0
23515    2
11239    2
15659    0
Name: support_needs, dtype: int64

In [19]:
X_valid.head(), y_valid.head()

(        age gender  tenure  frequent  payment_interval subscription_type  \
 10527  56.0      M    56.0      16.0               6.0            member
 15103  62.0      F    10.0      20.0              16.0            member
 2626   41.0      M    57.0      21.0               7.0            member
 28108  48.0      F    37.0       8.0               9.0              plus
 885    46.0      M    47.0      30.0               1.0               vip

        contract_length  after_interaction
 10527               30               10.0
 15103              360                7.0
 2626                90               23.0
 28108               90                5.0
 885                360                1.0  ,
 10527    1
 15103    1
 2626     0
 28108    1
 885      2
 Name: support_needs, dtype: int64)

In [31]:
from pycaret.classification import setup, compare_models

train_df = pd.concat([X_train, y_train], axis=1)

In [40]:
from sklearn.cluster import KMeans
X_train_kmeans = X_train.drop(columns=['gender', 'subscription_type'])
X_valid_kmeans = X_valid.drop(columns=['gender', 'subscription_type'])

kmeans = KMeans(n_clusters=3, random_state=42)
X_train['cluster'] = kmeans.fit_predict(X_train_kmeans)
X_valid['cluster'] = kmeans.predict(X_valid_kmeans)

In [41]:
from pycaret.classification import setup, compare_models, blend_models, finalize_model, predict_model

clf_setup = setup(data=train_df, target='support_needs', session_id=42, normalize=True)

In [42]:
train_df = pd.concat([X_train, y_train], axis=1)

In [44]:
top3_models = compare_models(n_select=3, exclude=['lightgbm'])

Initiated  . . . . . . . . . . . . . . . . . .             10:31:30
Status     . . . . . . . . . . . . . . . . . .    Loading Estimator
Estimator  . . . . . . . . . . . . . . . . . .  Logistic Regression

In [47]:
from pycaret.classification import blend_models, create_model

catboost_final = create_model('catboost')
blender = blend_models(estimator_list=top3_models, choose_better=True, method='soft', fold=5)

Original model was better than the blended model, hence it will be returned. NOTE: The display metrics are for the blended model (not the original one).

In [50]:
# 최종 모델 선정 = catBoost를 블렌더 모델
preds = predict_model(catboost_final, data=test_df)
preds[['ID', 'Label']].to_csv('submission.csv', index=False)

KeyError: "['Label'] not in index"